[Settings]

# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/user_demo.txt

# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/result.txt

# 更新时间显示位置，需要开启 open_update_time 才能生效，可选值：top、bottom，top: 显示于结果顶部，bottom: 显示于结果底部 | Update time display position, need to enable open_update_time to take effect, optional values: top, bottom, top: display at the top of the result, bottom: display at the bottom of the result
update_time_position = bottom

# 结果中偏好的本地源接口数量 | Preferred number of local source interfaces in the result
local_num = 20
